QdrantVectorStore new index creation fix
jerryjliu/llama_index pull request #1109
Opened 2023-04-08 08:11 UTC by Mikkolehtimaki

QdrantVectorStore was failing to create new collections with the HTTP client. Reason was that the check for already existing collections did not catch the correct exception from the failing `get_collection` call.

If a collection is not found, Qdrant Client throws an UnexceptedResponse. Added this to checking if collection exists.

@kacperlukawski what do you think of the solution?

2023-04-08 21:40 UTC, jerryjliu requested changes

2023-04-08 21:40 UTC, jerryjliu commented on gpt_index/vector_stores/qdrant.py
> +from qdrant_client.http.exceptions import UnexpectedResponse
this needs to be a lazy import

2023-04-09 10:01 UTC, joein commented
@Mikkolehtimaki @jerryjliu 

Looks like this is my mistake :(

I think `_create_collection` should look like this:

```Python
    def _collection_exists(self, collection_name: str) -> bool:
        """Check if a collection exists."""

        from grpc import RpcError
        from qdrant_client.http.exceptions import UnexpectedResponse
        
        try:
            self._client.get_collection(collection_name)
        except (UnexpectedResponse, RpcError):
            return False
        return True
```

2023-04-09 17:21 UTC, jerryjliu approved these changes

2023-04-09 17:21 UTC, jerryjliu commented
thanks!

2023-04-09 17:21 UTC, Mikkolehtimaki commented
Thanks for the feedback! I added the RPC error like @joein pointed out!

2023-04-09 17:33 UTC, merged