Add ElevenLabsTTS
jerryjliu/llama_index pull request #1381
Opened 2023-04-29 19:44 UTC by ravi03071991

Hi,

I have added TTS with ElevenLabs. We can generate audio of the response using the ElevenLabsTTS module.

Thank You.

2023-04-29 19:49 UTC, jerryjliu commented
> Hi,
> 
> I have added TTS with ElevenLabs. We can generate audio of the response using the ElevenLabsTTS module.
> 
> Thank You.

this is awesome!

2023-04-29 23:54 UTC, Disiok commented on gpt_index/tts/base.py
> +    def generate_elevenlabs_audio(self, text: str, voice: Optional[str] = None) -> None:
As comment as other PR, let's make sure the interface is consistent?

2023-04-29 23:55 UTC, Disiok requested changes
Similar comments as other PR.

2023-05-01 00:12 UTC, jerryjliu approved these changes

2023-05-01 00:12 UTC, merged