Added optional num parameter for dataset generation
jerryjliu/llama_index pull request #3509
Opened 2023-05-18 08:35 UTC by sahil-springworks

### Summary

Added a new optional `num` parameter to the dataset `generate_questions_from_nodes` function allowing users to fetch only "num" number of questions from the given nodes.

2023-05-18 17:37 UTC, Disiok requested changes
Thanks for the contribution! Minor comment on cleaner implementation of this

2023-05-19 01:11 UTC, sahil-springworks commented on llama_index/evaluation/dataset_generation.py
> +            if num != None and len(questions) >= num:
Actually `num` is not the number of nodes that need to be evaluated but instead the number of questions that need to be generated so we need to check for the length of the questions.

2023-05-19 02:39 UTC, Disiok commented on llama_index/evaluation/dataset_generation.py
> +            if num != None and len(questions) >= num:
Oh I see, each iteration can generate multiple questions. Sorry totally missed this!

2023-05-19 02:40 UTC, Disiok commented on llama_index/evaluation/dataset_generation.py
> +            if num != None and len(questions) >= num:
very nit: more idiomatic in Python to do `num is not None`

2023-05-19 02:40 UTC, Disiok approved these changes

2023-05-19 02:41 UTC, Disiok commented
Thanks! Happy to merge after fixing the nit and passing CI

2023-05-19 04:07 UTC, sahil-springworks commented
> Thanks! Happy to merge after fixing the nit and passing CI

Made the change to use `num is not None`

2023-05-19 06:17 UTC, jerryjliu approved these changes
approving with one nit

2023-05-19 06:17 UTC, jerryjliu commented on llama_index/evaluation/dataset_generation.py
> +        if num != None:
can you do `num is not None` here too

2023-05-19 07:01 UTC, sahil-springworks commented on llama_index/evaluation/dataset_generation.py
> +        if num != None:
> can you do `num is not None` here too

Sure, sorry to have missed that. Done.

2023-05-21 07:19 UTC, jerryjliu approved these changes

2023-05-22 04:37 UTC, sahil-springworks commented
@Disiok @jerryjliu any action needed from my side for the merge of this PR?

2023-05-25 21:31 UTC, logan-markewich commented
@sahil-springworks looks like mypy is noticing a missing type annotation here. With that fixed it should be good to go

`llama_index/evaluation/dataset_generation.py:119: error: Need type annotation for "questions" (hint: "questions: List[<type>] = ...")  [var-annotated]`

2023-05-26 01:38 UTC, sahil-springworks commented
@logan-markewich added. Thanks

2023-05-26 03:29 UTC, logan-markewich commented
Thanks!!

2023-05-26 03:30 UTC, merged